const palette = {
  tealGreen: "#128c7e",
  tealGreenDark: "#075e54",
  green: "#25d366",
  lime: "#dcf8c6",
  skyblue: "#34b7f1",
  smokeWhite: "#ece5dd",
  white: "white",
  gray: "#3C3C3C",
  lightGray: "#757575",
  iconGray: "#717171",
  text: "#232323",
  textlight: "#ACA9A9",
  LightishGray: "#23232366",
  Purple: "#8489FC",
  Bluish: "#8489FC",
  greish: "#F8F8F8",
};

export const theme = {
  colors: {
    background: palette.white,
    foreground: palette.tealGreenDark,
    primary: palette.tealGreen,
    tertiary: palette.lime,
    secondary: palette.Purple,
    white: palette.white,
    text: palette.text,
    lighttext: palette.textlight,
    secondaryText: palette.lightGray,
    iconGray: palette.iconGray,
    placeHolder: palette.LightishGray,
    Bluish: palette.Bluish,
    listback: palette.greish,
  },
};
